/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -i appearance_interface.h -p :appearance_interface.cpp ../dde-wallpaper-chooser/dbus/com.deepin.daemon.Appearance.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "appearance_interface.h"
/*
 * Implementation of interface class ComDeepinDaemonAppearanceInterface
 */

ComDeepinDaemonAppearanceInterface::ComDeepinDaemonAppearanceInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

ComDeepinDaemonAppearanceInterface::~ComDeepinDaemonAppearanceInterface()
{
}

