/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -l DBusFileManager1 -i /home/lmh/0305/fantascene-dynamic-wallpaper/dde-desktop/src/dde-desktop/dbus/filemanager1/dbusfilemanager1.h -a filemanager1_adaptor.h: dbus/filemanager1/org.freedesktop.FileManager1.xml
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef FILEMANAGER1_ADAPTOR_H
#define FILEMANAGER1_ADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "/home/lmh/0305/fantascene-dynamic-wallpaper/dde-desktop/src/dde-desktop/dbus/filemanager1/dbusfilemanager1.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface org.freedesktop.FileManager1
 */
class FileManager1Adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.freedesktop.FileManager1")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.freedesktop.FileManager1\">\n"
"    <method name=\"ShowFolders\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"URIs\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"StartupId\"/>\n"
"    </method>\n"
"    <method name=\"ShowItems\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"URIs\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"StartupId\"/>\n"
"    </method>\n"
"    <method name=\"ShowItemProperties\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"URIs\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"StartupId\"/>\n"
"    </method>\n"
"    <method name=\"GetMonitorFiles\">\n"
"      <arg direction=\"out\" type=\"as\" name=\"URIs\"/>\n"
"    </method>\n"
"    <method name=\"Trash\">\n"
"      <arg direction=\"in\" type=\"as\" name=\"URIs\"/>\n"
"    </method>\n"
"    <signal name=\"lockEventTriggered\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"user\"/>\n"
"    </signal>\n"
"    <method name=\"topTaskDialog\">\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"closeTask\"/>\n"
"  </interface>\n"
        "")
public:
    FileManager1Adaptor(DBusFileManager1 *parent);
    virtual ~FileManager1Adaptor();

    inline DBusFileManager1 *parent() const
    { return static_cast<DBusFileManager1 *>(QObject::parent()); }

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QStringList GetMonitorFiles();
    void ShowFolders(const QStringList &URIs, const QString &StartupId);
    void ShowItemProperties(const QStringList &URIs, const QString &StartupId);
    void ShowItems(const QStringList &URIs, const QString &StartupId);
    void Trash(const QStringList &URIs);
    void closeTask();
    bool topTaskDialog();
Q_SIGNALS: // SIGNALS
    void lockEventTriggered(const QString &user);
};

#endif
