.TH fantascene-dynamic-wallpaper 1  "September 25, 2022" "version 1" "General Commands Manual"

.SH NAME
fantascene\-dynamic\-wallpaper \-  Fantascene Dynamic Wallpaper 

.SH SYNOPSIS
.B fantascene\-dynamic\-wallpaper

.SH DESCRIPTION
.B Fantascene Dynamic Wallpaper
is a dynamic wallpaper software running in X11 desktop environment .

.SH OPTIONS
.PP
This program does not accept any command line options.

.PP
This manual page was written by
.MT liuminghang0821@\:gmail.com
 Liu MingHang
.ME
for the Debian project (and may be used by others).
